In [10]:
# in order to compute the variation of the TLE angles over time.
import numpy as np

In [11]:
filename = "../data/teme/ISS_tles.txt"
with open(filename, "r") as f:
  lines = f.readlines()

In [12]:
L=[]
for i in range(0, len(lines)):
    L.append([float(lines[i].split()[j]) for j in range(7)])

In [48]:
# compute the orbital elements:
r = np.array([L[i][1:4] for i in range(len(L))])
v = np.array([L[i][4:7] for i in range(len(L))])
h = np.cross(r, v)
n = np.cross(np.array([0, 0, 1]), h)
GM = 398600.4415e+9
e_vec = np.cross(v, h)/GM - r/np.linalg.norm(r, axis=1)[:, None]
e = np.linalg.norm(e_vec, axis=1)
i = np.arccos(h[:, 2]/np.linalg.norm(h, axis=1))
Omega = np.arccos(n[:, 0]/np.linalg.norm(n, axis=1))
if (n[:, 1] < 0).any():
    Omega[n[:, 1] < 0] = 2*np.pi - Omega[n[:, 1] < 0]
# omega = np.arccos(np.sum(n*e_vec, axis=1)/(np.linalg.norm(n, axis=1)*e))
omega = np.arccos(np.dot(n, e_vec.T)/(np.linalg.norm(n, axis=1)*e))
if (e_vec[:, 2] < 0).any():
    omega[e_vec[:, 2] < 0] = 2*np.pi - omega[e_vec[:, 2] < 0]
# nu = np.arccos(np.dot(e_vec, r.T)/(e*np.linalg.norm(r, axis=1)))
# if (np.dot(r, v.T) < 0).any():
#     nu[np.dot(r, v.T) < 0] = 2*np.pi - nu[np.dot(r, v.T) < 0]
a = np.linalg.norm(h, axis=1)**2/(GM*(1 - e**2))

# Convert to degrees
i = np.rad2deg(i)
Omega = np.rad2deg(Omega)
omega = np.rad2deg(omega)

/tmp/ipykernel_8468/3525068472.py:14: RuntimeWarning: invalid value encountered in arccos
  omega = np.arccos(np.dot(n, e_vec.T)/(np.linalg.norm(n, axis=1)*e))


In [50]:
e

array([2.31564133e-04, 8.67960171e-04, 1.19292600e-03, 8.65540305e-04,
       1.86577810e-04, 4.63571643e-04, 1.14206196e-03, 3.48282746e-04,
       8.63300875e-04, 9.45321566e-04, 6.77213206e-04, 2.45689467e-04,
       1.01921153e-04, 4.32621047e-04, 9.78326058e-05, 2.17783110e-04,
       1.67381722e-04, 5.04885392e-04, 5.91943350e-04, 6.08229352e-05,
       1.35885384e-04, 1.00896735e-03, 1.29903554e-03, 9.41598723e-04,
       2.59578111e-04, 7.51088627e-04, 1.27221150e-03, 1.02221253e-03,
       6.44232308e-04, 3.86975849e-04, 3.65889370e-04, 1.14705023e-03,
       7.40337836e-04, 6.19972715e-04, 3.75936237e-04, 1.12720881e-03,
       1.02423513e-03, 5.52724530e-04, 9.09981244e-04, 2.97952608e-04,
       6.71264671e-04, 9.48968188e-04, 7.13149528e-05, 6.27195603e-04,
       7.84542427e-05, 1.76610103e-04, 5.66061292e-04, 1.07784231e-03,
       8.72299169e-04, 6.52163154e-04, 2.52255413e-04, 4.42418517e-04,
       7.47814691e-04, 2.93338910e-04, 4.79268542e-04, 1.90222214e-04,
      

In [39]:
omega

array([1.06613721e+02, 1.32712920e+02, 1.45851601e+02, 6.46286304e+01,
       1.03198002e+02, 8.80152373e+01, 1.45903635e+02, 3.44855124e+02,
       6.17926416e+01, 4.96466489e+01, 1.27847470e+02, 9.72512840e+01,
       3.35599734e+02, 1.20551129e+02, 1.03212958e+02, 1.12578216e+02,
       9.94450317e+01, 3.50136233e+02, 7.60101894e+01, 1.06234950e+02,
       1.00074460e+02, 1.43497663e+02, 1.72867566e+02, 1.97437987e+02,
       1.15236318e+02, 1.34286027e+02, 1.64617724e+02, 1.46071538e+02,
       3.55364476e+02, 9.47616309e+01, 2.17972066e+02, 1.51936218e+02,
       5.70736353e+01, 2.07119441e+02, 1.20263086e+02, 1.92307971e+02,
       1.48974171e+02, 7.28290661e+01, 2.48831607e+01, 1.17568461e+02,
       1.32536483e+02, 1.45270848e+02, 1.03183356e+02, 6.35011411e+01,
       1.05957879e+02, 9.67047555e+01, 1.28577866e+02, 1.54428480e+02,
       1.42241737e+02, 5.84418017e+01, 9.17451380e+01, 7.65490090e+01,
       1.37111328e+02, 3.35405793e+02, 6.96098072e+01, 9.51152869e+01,
      

In [40]:
e

array([0.95969956, 0.96027435, 0.96055915, 0.95946224, 0.95959907,
       0.95941868, 0.96050429, 0.95963982, 0.9594741 , 0.95963495,
       0.9600767 , 0.95948665, 0.95947214, 0.95986381, 0.95951646,
       0.95968645, 0.95946735, 0.95981729, 0.95934548, 0.95954489,
       0.95944718, 0.96036366, 0.96065769, 0.96031838, 0.95969421,
       0.9601065 , 0.96062458, 0.96036745, 0.95994168, 0.95930748,
       0.95970186, 0.96056094, 0.95952141, 0.96001719, 0.95976983,
       0.96053801, 0.96036337, 0.95933347, 0.96003403, 0.95967793,
       0.96001364, 0.96028419, 0.95941462, 0.95943268, 0.9594466 ,
       0.95933453, 0.95989463, 0.96041407, 0.9601943 , 0.9595134 ,
       0.95928907, 0.95930511, 0.96003781, 0.95972629, 0.95937636,
       0.95930033, 0.9593556 , 0.95997617, 0.95997091, 0.95935833,
       0.95957167, 0.96040339, 0.95929437, 0.9601164 , 0.95931847,
       0.9592751 , 0.96025038, 0.95938245, 0.95984193, 0.95936893,
       0.9592909 , 0.95988854, 0.95931873, 0.95937707, 0.96033